
### get
GET http://localhost:26769/health


### post
POST http://localhost:26769/ HTTP/1.1
content-type: application/json

{
    "value": true
}


### new idea
POST http://localhost:26769/api/ideas/new
content-type: application/json

{
    "user_id": "lpkpvtsynueh2vn",
    "description": "A test description",
    "problem": "A test problem",
    "customer": "A test customer",
    "founder_specific": "A test founder specific"
}
